import { IMAGES } from "../constants";

export default [
  {
    id: 1,
    title: "Sneakers",
    image: IMAGES.shoes,
    products: [
      {
        product_id: 1,
        title: "Mens Kinetic™ Rush Ripstop Sneaker",
        price: "1299",
        rating: "3.8",
        discount: "20%",
        isFavorite: false,
        bgColor: "#EAFBB3",
      },
      {
        product_id: 2,
        title: "Mens Caribou™ Low Sneaker WP",
        price: "1029",
        rating: "3.8",
        discount: "20%",
        isFavorite: true,
        bgColor: "#FBE1B3",
      },
      {
        product_id: 3,
        title: "Men's Madson™ II Hiker Boot",
        price: "8021",
        rating: "2.9",
        discount: "30%",
        isFavorite: false,
        bgColor: "#B3D1FB",
      },
      {
        product_id: 4,
        title: "Men's Kezar™ Chelsea Boot",
        price: "2999",
        rating: "4.5",
        discount: "10%",
        isFavorite: false,
        bgColor: "#B3FBE4",
      },
      {
        product_id: 5,
        title: "II Hiker Boot",
        price: "6021",
        rating: "3.9",
        discount: "20%",
        isFavorite: false,
        bgColor: "#FBE1B3",
      },
      {
        product_id: 6,
        title: "Chelsea Boot",
        price: "4999",
        rating: "4.5",
        discount: "10%",
        isFavorite: false,
        bgColor: "#B3FBE4",
      },
    ],
  },
  {
    id: 2,
    title: "Watch",
    image: IMAGES.watch,
    products: [
      {
        product_id: 1,
        title: "Omega",
        price: "1400",
        rating: "4.3",
        discount: "20%",
        isFavorite: false,
        bgColor: "#B3FBE4",
      },
      {
        product_id: 2,
        title: "H. Moser & Cie.",
        price: "1200",
        rating: "3.8",
        discount: "10%",
        isFavorite: false,
        bgColor: "#B3D1FB",
      },
      {
        product_id: 3,
        title: "Girard-Perregaux",
        price: "1420",
        rating: "4.8",
        discount: "30%",
        isFavorite: false,
        bgColor: "#EAFBB3",
      },
      {
        product_id: 4,
        title: "Louis Moinet",
        price: "2010",
        rating: "4.9",
        discount: "40%",
        isFavorite: false,
        bgColor: "#EAFBB3",
      },
    ],
  },
  {
    id: 3,
    title: "Backpack",
    image: IMAGES.bag,
    products: [
      {
        product_id: 1,
        title: "",
        price: "",
        rating: "",
        discount: "",
        isFavorite: false,
        bgColor: "#EAFBB3",
      },
      {
        product_id: 2,
        title: "",
        price: "",
        rating: "",
        discount: "",
        isFavorite: false,
        bgColor: "#FBE1B3",
      },
      {
        product_id: 3,
        title: "",
        price: "",
        rating: "",
        discount: "",
        isFavorite: false,
        bgColor: "#B3D1FB",
      },
      {
        product_id: 4,
        title: "",
        price: "",
        rating: "",
        discount: "",
        isFavorite: false,
        bgColor: "#B3FBE4",
      },
    ],
  },
];
